services:
  nginx-lb:
    image: vipunsanjana/nginx-lb:latest
    ports:
      - "80:80"
    networks:
      - mern-net
    depends_on:
      - backend1
      - backend2
      - frontend1
      - frontend2
    restart: unless-stopped
