version: '3.8'

services:
  backend1:
    image: vipunsanjana/backend:latest
    networks:
      - mern-net
    restart: unless-stopped

  backend2:
    image: vipunsanjana/backend:latest
    networks:
      - mern-net
    restart: unless-stopped

  frontend:
    image: vipunsanjana/frontend:latest
    networks:
      - mern-net
    restart: unless-stopped

  nginx-lb:
    image: vipunsanjana/nginx-lb:latest
    ports:
      - "80:80"    # expose nginx on host port 80
    networks:
      - mern-net
    depends_on:
      - backend1
      - backend2
      - frontend
    restart: unless-stopped

networks:
  mern-net:
    driver: bridge
