version: '3.8'

services:
  backend1:
    image: vipunsanjana/backend
    container_name: backend1
    networks:
      - mern-net
    ports:
      - "5001:5000"    # map container port 5000 to host port 5001
    restart: unless-stopped

  backend2:
    image: vipunsanjana/backend
    container_name: backend2
    networks:
      - mern-net
    ports:
      - "5002:5000"
    restart: unless-stopped

  frontend:
    image: vipunsanjana/frontend
    container_name: frontend
    networks:
      - mern-net
    restart: unless-stopped

  nginx-lb:
    build:
      context: .
      dockerfile: ./nginx-lb/Dockerfile
    container_name: nginx-lb
    ports:
      - "80:80"
    networks:
      - mern-net
    depends_on:
      - backend1
      - backend2
      - frontend
    restart: unless-stopped

networks:
  mern-net:
    driver: bridge


    