version: '3.8'

services:
  backend1:
    image: vipunsanjana/backend
    container_name: backend1
    networks:
      - mern-net
    restart: unless-stopped

  backend2:
    image: vipunsanjana/backend
    container_name: backend2
    networks:
      - mern-net
    restart: unless-stopped

  frontend:
    image: vipunsanjana/frontend
    container_name: frontend
    networks:
      - mern-net
    restart: unless-stopped

  nginx-lb:
    image: vipunsanjana/nginx-lb
    container_name: nginx-lb
    ports:
      - "80:80"
    networks:
      - mern-net
    depends_on:
      - backend1
      - backend2
      - frontend
    restart: unless-stopped

networks:
  mern-net:
    driver: bridge


    