name: MERN Production Deployment

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_ACCESS_TOKEN }}
        
        
    - name: Build and push backend
      run: |
        docker build -t $DOCKERHUB_USERNAME/backend:latest ./backend
        docker push $DOCKERHUB_USERNAME/backend:latest
        
    - name: Build and push frontend
      run: |
        docker build -t $DOCKERHUB_USERNAME/frontend:latest ./frontend
        docker push $DOCKERHUB_USERNAME/frontend:latest
        
    - name: Build and push nginx-lb
      run: |
        docker build -t $DOCKERHUB_USERNAME/nginx-lb:latest ./nginx-lb
        docker push $DOCKERHUB_USERNAME/nginx-lb:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Stop and remove containers
      run: docker-compose down || true
      
    - name: Pull latest images
      run: |
        docker pull $DOCKERHUB_USERNAME/backend:latest
        docker pull $DOCKERHUB_USERNAME/frontend:latest
        docker pull $DOCKERHUB_USERNAME/nginx-lb:latest
        
    - name: Start services
      run: docker-compose up -d