name: MERN Production Deployment

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  COMPOSE_PROJECT_NAME: vipunsanjana

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push backend
        run: |
          docker build -t $DOCKERHUB_USERNAME/backend:latest ./backend
          docker push $DOCKERHUB_USERNAME/backend:latest

      - name: Build and push frontend
        run: |
          docker build -t $DOCKERHUB_USERNAME/frontend:latest ./frontend
          docker push $DOCKERHUB_USERNAME/frontend:latest

      - name: Build and push nginx-lb
        run: |
          docker build -t $DOCKERHUB_USERNAME/nginx-lb:latest ./nginx-lb
          docker push $DOCKERHUB_USERNAME/nginx-lb:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Free port 80
        run: |
          # Stop any containers using port 80
          docker stop $(docker ps -q --filter publish=80) 2>/dev/null || true
          docker rm $(docker ps -aq --filter publish=80) 2>/dev/null || true
          
          # Kill any host processes using port 80
          sudo fuser -k 80/tcp || true
          sleep 2

      - name: Stop and remove containers
        run: |
          docker-compose -p $COMPOSE_PROJECT_NAME down || true

      - name: Pull latest images
        run: |
          docker pull $DOCKERHUB_USERNAME/backend:latest
          docker pull $DOCKERHUB_USERNAME/frontend:latest
          docker pull $DOCKERHUB_USERNAME/nginx-lb:latest

      - name: Start services
        run: docker-compose -p $COMPOSE_PROJECT_NAME up -d