name: Build, Push Docker images & Deploy to EC2

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:latest ./backend

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend:latest ./frontend

      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:latest

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend:latest

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: ec2_key.pem
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend:latest
            docker stop backend_5001 || true
            docker rm backend_5001 || true
            docker run -d --name backend_5001 -p 5001:5000 ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:latest
            docker stop backend_5002 || true
            docker rm backend_5002 || true
            docker run -d --name backend_5002 -p 5002:5000 ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend:latest
            docker stop nginx_lb || true
            docker rm nginx_lb || true
            docker run -d --name nginx_lb -p 80:80 -v ~/mern-app/scripts/nginx_lb.conf:/etc/nginx/conf.d/default.conf nginx:alpine
